.TH client_static 1 "September 2025" "v0.2.1" "Client_static"
.SH NAME
client_static \- demo program using libmyutils.a
.SH SYNOPSIS
.B client_static
.I filename
.SH DESCRIPTION
The
.B client_static
program demonstrates the usage of functions provided by
.B libmyutils.a
including string manipulation and file utilities.

The program accepts a filename as argument and performs:
- Word, line, and character counting.
- Simple string search (grep-like functionality).

.SH AUTHOR
Muhammad Rizwan <mr0039747@gmail.com>
