.TH client_dynamic 1 "September 2025" "v0.2.1" "Client_dynamic"
.SH NAME
client_dynamic \- demo program using libmyutils.so
.SH SYNOPSIS
.B client_dynamic
.I filename
.SH DESCRIPTION
The
.B client_synamic
program demonstrates the usage of functions provided by
.B libmyutils.so
including string manipulation and file utilities.

The program accepts a filename as argument and performs:
- Word, line, and character counting.
- Simple string search (grep-like functionality).

.SH AUTHOR
Muhammad Rizwan <mr0039747@gmail.com>
